### ISSUE TITLE
First predicted value of `smooth` is NaN

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaPlots/AlgebraOfGraphics.jl#102]
I noticed this because it shows a bug in CairoMakie, which causes the second point of the line to be connected to the graphic's origin, while the first point is missing. You can see it in your docs, too. The first smooth has a straight line jutting off on the left.

While I'm going to fix this in CairoMakie, so that a NaN in first position doesn't trip it up, I guess you still want to fix it here as well.

![grafik](https://user-images.githubusercontent.com/22495855/96241914-1f0d8e00-0fa3-11eb-8547-a0136105363d.png)

**Comment by jkrumbiegel** [comment]
haha github thinking it's smart, closing my issues without my consent

**Comment by piever** [comment]
This seems to be an issue with Loess.jl: https://github.com/JuliaStats/Loess.jl/issues/28, though it seems somewhat fixed by https://github.com/JuliaStats/Loess.jl/pull/42. Closing here as any remaining cases (if they exist) should be fixed upstream.
