### ISSUE TITLE
Axis labels don't show up

### ISSUE THREAD

**Issue by ericphanson** [JuliaPlots/AlgebraOfGraphics.jl#104]
I've been trying to follow the [first example in the 0.1.2 tutorial](http://juliaplots.org/AlgebraOfGraphics.jl/stable/generated/tutorial/#Working-with-tables-1), but the axis labels don't show up for me:

![scatter](https://user-images.githubusercontent.com/5846501/96862996-82496580-1466-11eb-9068-d9b1c099b9fe.png)

(with SVG or PNG, but Github doesn't let me upload the SVG). This was produced by cloning the repo, checking out the 0.1.2 tag, starting Julia 1.4.2 with `julia --project=docs`, doing `] dev .` to dev AlgebraOfGraphics, then running the tutorial code.

I think it must be due to different versions of dependencies and transitive dependencies, but I've been having a lot of trouble tracking it down. There is some weird stuff, like the 0.1.2 tag of AlgebraOfGraphics has [AbstractPlotting compat'd to 0.12](https://github.com/JuliaPlots/AlgebraOfGraphics.jl/blob/v0.1.2/Project.toml) but the [checked-in docs manifest has Abstractplotting at 0.9.27](https://github.com/JuliaPlots/AlgebraOfGraphics.jl/blob/45b1bb9b2166ac8fa07a89d01d08a317a38029ab/docs/Manifest.toml#L13). I think what happens is that in the [`Pkg.develop` step of the Travis docs build](https://github.com/JuliaPlots/AlgebraOfGraphics.jl/blob/45b1bb9b2166ac8fa07a89d01d08a317a38029ab/.travis.yml#L27) the package resolver chooses new versions of all the dependencies and updates its local copy of the Manifest, then generates the docs, and that Manifest is never checked in (which also happens with my local `] dev .` step). So I'm not actually sure how to repro the docs environment to try to get axis labels. However, if you want to repro my environment that does not have axis labels, here's the Manifest and Project I get after `] dev .` in the docs project:

[no-axis-label-env.zip](https://github.com/JuliaPlots/AlgebraOfGraphics.jl/files/5422210/no-axis-label-env.zip)

By the way, I think the reproducibility problem for the docs build can be solved by checking in a Manifest with AlgebraOfGraphics already dev'd by a relative path, and then not `dev`ing it during the docs build step, to not let the resolver alter the Manifest.

**Comment by piever** [comment]
Turns out I was working around a hack in MakieLayout that was fixed in the main time, which in turn broke my hack...

Everything should be working on master (I'll tag a release in a little bit).
