### ISSUE TITLE
Scale things so text doesn't overlap other objects

### ISSUE THREAD

**Issue by jtrakk** [JuliaPlots/AlgebraOfGraphics.jl#121]
Sometimes a facet label text overlaps its bounding box or two scales have text that touch. These fonts could be scaled down to fit inside the container or the box could be scaled up to fit the text or both.

![image](https://user-images.githubusercontent.com/43392409/99307651-a6048f00-280b-11eb-8d2d-1850b120b032.png)

![image](https://user-images.githubusercontent.com/43392409/99439720-6c468d80-28ca-11eb-9112-609663f247c0.png)

Is this issue a better fit for here or for AbstractPlotting?

**Comment by jtrakk** [comment]
In this example, the legend goes over the edge. An improvement would be 

- shrinking the legend to fit, or
- expanding the plot boundary to fit

```julia
data(diamonds) * mapping(:Price, :Price, color=:Color, size=:Clarity, marker=:Cut) * visual(Scatter) |> draw
```
![image](https://user-images.githubusercontent.com/43392409/99438842-39e86080-28c9-11eb-84e9-2eefdb1736cd.png)

**Comment by piever** [comment]
One can now pass axis dimensions explicitly to fix this, as in http://juliaplots.org/AlgebraOfGraphics.jl/dev/generated/penguins/#Frequency-plots.
