### ISSUE TITLE
Clarify vertical axis label for density plots

### ISSUE THREAD

**Issue by jtrakk** [JuliaPlots/AlgebraOfGraphics.jl#122]
On a plot with `AlgebraOfGraphics.density`, it's not clear what the vertical scale means. It could be rescaled to 1, or not shown, or at least clarified what it means.
![image](https://user-images.githubusercontent.com/43392409/99308018-275c2180-280c-11eb-95f4-9fe04078195e.png)

**Comment by piever** [comment]
Closed by #155
