### ISSUE TITLE
Compatibility of pair syntax with DataFrames

### ISSUE THREAD

**Issue by knuesel** [JuliaPlots/AlgebraOfGraphics.jl#180]
It was noted on [Discourse](https://discourse.julialang.org/t/upcoming-algebraofgraphics-release/60968) that the pair syntax for mappings is close to the DataFrames but  note quite compatible. I thought it would be nice to have a place to summarize the issue and document the decision (hope you don't mind!).

**Single rows vs columns**

The main issue is that AlgebraOfGraphics mappings work on single rows instead of whole columns. For example this

```julia
:bill_length_mm => (t -> t + 10) => "bill length (cm)"
```
must be adapted for DataFrames to:

```julia
:bill_length_mm => (t -> t .+ 10) => "bill length (cm)"
```

or

```julia
:bill_length_mm => ByRow(t -> t + 10) => "bill length (cm)"
```

Advantages of single rows include:

* Simpler for the user in most cases.
* Less error prone especially
   * with grouped data (should a column operation apply to each group or the whole dataset?)
   * when several datasets are used

Downsides include
* No support for operations that require the whole column (for example z-score standardisation)
* Risk of confusion with DataFrames API
* Transformations cannot be reused between DataFrames and AlgebraOfGraphics

**Tuples vs arrays**

Another point I noticed in the machine learning tutorial section: AlgebraOfGraphics allows giving multiple input variables as a tuple:

```julia
error_rate = (:species, :predicted_species) => !isequal => "error rate"
```

In DataFrames only arrays are allowed:

```julia
error_rate = [:species, :predicted_species] => ByRow(!isequal) => "error rate"
```

I personally like arrays here as they stand out more in the middle of function calls, but that's subjective of course.

**Comment by piever** [comment]
Yes, the description seems correct. I've added a small demo on using some ML techniques in combinations with AlgebraOfGraphics in the tutorial (in [this section](http://juliaplots.org/AlgebraOfGraphics.jl/dev/generated/penguins/#Machine-Learning)), mainly to show that transformations that require the whole column should be applied before-hand, so the same would apply to z-scoring.

About `Tuple`s versus `Array`s, a possible style guide is to use `Tuple` when passing the arguments to a function (many inputs, one output), and only use `Array` when selecting several variables as in [wide-format data](http://juliaplots.org/AlgebraOfGraphics.jl/dev/generated/gallery/#Wide-data).

**Comment by piever** [comment]
Btw, I'm adding the documentation part of your post in the docs, as part of #182, because I think it's very informative. The "comparison with DataFrames" bit should probably go in a FAQ section in the future.

**Comment by piever** [comment]
Update: actually the "internal style guide" to use `Tuple` for passing many arguments to an operation may well become enforced, because I plan to support pregrouped data, as in #79, and also supporting an array for "many-to-one" operations would create too much confusion, as it becomes less clear whether `[a, b, c] => f` means `map(f, a, b, c)` or `[map(f, a), map(f, b), map(f, c)]`.
