### ISSUE TITLE
Formalisation of algebra

### ISSUE THREAD

**Issue by knuesel** [JuliaPlots/AlgebraOfGraphics.jl#184]
I've been playing with the layer algebra a bit, and I'd be happy to try and write a formal description of the algebraic structure, which could serve as documentation. Would you be interested? It could also serve to check if the current structure has the desired properties.

What got me thinking about this is distributivity: in AlgebraOfGraphics `*` appears to distribute over `+`. But the algebra has the particularity that addition is non-commutative (the user can write `a+b` or `b+a` depending on which layer should be drawn on top). But distributivity generally implies the commutativity of `+` (see the simple proof [here](https://math.stackexchange.com/a/702626/549289) for example). So what's going on?

It turns out that `*` is right-distributive over `+`, but not left-distributive. Here's a counter-example, using layers that only contain positional mappings for simplicity:

```julia
# Concise print for layers, e.g. mapping(:a, :b) + mapping(:c) will print as (a,b) (c)
function Base.show(io::IO, s::AlgebraOfGraphics.OneOrMoreLayers)
    l::AlgebraOfGraphics.Layers = s
    print(io, join(["("*join(layer.positional, ",")*")" for layer in l.layers], " "))
end

# Define some simple layers
x = mapping(:x)
y = mapping(:y)
a = mapping(:a)
b = mapping(:b)
```

Distributivity works in simple cases:

```julia
julia> a*(x+y)
(a,x) (a,y)

julia> a*x + a*y
(a,x) (a,y)

julia> (x+y)*a
(x,a) (y,a)

julia> x*a + y*a
(x,a) (y,a)
```

But only right-distributivity works in more  complex cases:

```julia
julia> c = a+b
(a) (b)

julia> z = x+y
(x) (y)

julia> (x+y)*c
(x,a) (x,b) (y,a) (y,b)

julia> x*c + y*c           # Same as (x+y)*c
(x,a) (x,b) (y,a) (y,b)

julia> c*(x+y)
(a,x) (a,y) (b,x) (b,y)

julia> c*x + c*y           # Different from c*(x+y) !
(a,x) (b,x) (a,y) (b,y)
```

We could easily trade right-distributivity for left-distributivity by swapping the loops in https://github.com/JuliaPlots/AlgebraOfGraphics.jl/blob/dd8f9dc58f3e73b31c423e3e1bd5e7da311e1d5f/src/algebra/layers.jl#L22.

**Comment by piever** [comment]
Docs PR are always welcome! I guess extra information about the algebra could go in http://juliaplots.org/AlgebraOfGraphics.jl/dev/layers/operations/

Re: lack of left-distributivity. One thing that may be worth mentioning is that this is mostly a theoretical concern. In practice, in the reasonably extensive tutorial and example gallery, I don't think there is ever a case where one does `(a + b) * (c + d)`.

**Comment by knuesel** [comment]
Indeed! Though one never knows what users will come up with :) (and the possibility to do it is advertised at the bottom of `operations.md`).

Am I right that the order of layers only affects which is drawn on top of which?

**Comment by piever** [comment]
> Am I right that the order of layers only affects which is drawn on top of which? That makes it even more minor.

Yes, that's correct. Basically if `Layers` was stored with an unordered container, the distributivity would hold exactly.

**Comment by jtrakk** [comment]
I wonder if it would be good to regain commutative addition by making layers blend by default instead of having the front layer block the behind layer. Looking through the gallery I don't see examples where it would be obviously bad to blend.

**Comment by knuesel** [comment]
Interesting... But I don't think that would be a good default. For example, this looks fine:

![image](https://user-images.githubusercontent.com/2412819/119477581-5caf7200-bd4f-11eb-85bc-e9f88f51e41e.png)

But applying a "multiply" blend in Inkscape I find the result much less neat:

![image](https://user-images.githubusercontent.com/2412819/119477555-58835480-bd4f-11eb-821d-e51aaf7b95e6.png)

Opaque layers in user-specified order are probably a more natural default, and alpha or blending should be applied when the user asks for it.

I think the non-commutativity of `+` is a nice way to specify the order of layers. Non-distributivity follows from the fact that `(a+b) * (x+y)` gives four layers `a*x`, `b*x`, `a*y`, `b*y` and there is no way to preserve both the "b over a" and the "y over x" orders. Right-distributivity gives a simple rule, easy to document: **the order among layers on the left of `*` is always preserved**. In this sense it is good that `c * (x + y) != c*x + c*y` when `c` is composite (e.g. `c = a + b`). Otherwise you would have `a*y` after `b*x` which would violate the order guarantee.

**Comment by knuesel** [comment]
Here's an illustration of the algebra expressiveness:

Say we want to show two datasets on the same plot:

```julia
using AlgebraOfGraphics, DataFrames, CairoMakie, Distributions, Random

set_aog_theme!()

Random.seed!(5151)

dist1 = TruncatedNormal(0, 1, -1, 1)
dist2 = TruncatedNormal(1, 1, -1, 1)
df1 = DataFrame(x=rand(dist1, 100),    y=rand(dist1, 100),    source=rand(["a+", "a-"], 100))
df2 = DataFrame(x=rand(dist2,  50).+1, y=rand(dist2,  50).+1, source=rand(["b+", "b-"],  50))
```

**First case:** we want to show density heatmaps + contours. The data regions overlap a bit... one option is to show one dataset on top of the other.

The rule says "order on the left of `*` is preserved" so we set the dataset order on the left:

```julia
axis=(width=400, height=300)

plt = (data(df1) + data(df2)) *                     # Order of datasets preserved globally
    mapping(:x, :y) *
    AlgebraOfGraphics.density() *
    (mapping() + visual(Contour, colormap=:grayC))  # Order of visualizations preserved only for each dataset

draw(plt; axis)
```

The result shows as expected all visualizations for `df1` under `df2`:

![image](https://user-images.githubusercontent.com/2412819/119493618-ac4a6980-bd60-11eb-9c78-a337ed9a6063.png)

Maybe not a great visualization, but it looks better than preserving the order of "contours above heatmaps" across datasets:

```julia
plt = mapping(:x, :y) *
    AlgebraOfGraphics.density() *
    (mapping() + visual(Contour, colormap=:grayC)) *  # All contours above all heatmaps
    (data(df1) + data(df2))

draw(plt; axis)
```

![image](https://user-images.githubusercontent.com/2412819/119493855-efa4d800-bd60-11eb-98e4-07011905ff7f.png)

**Second case:** We want no heatmaps, but markers (scatter plot). Now it seems better to show all contours in the background, and all markers on the top. The global order of "markers above contours" is enforced by writing that on the left of `*`:

```julia
contour = AlgebraOfGraphics.density() * visual(Contour, colormap=:grayC)

plt = mapping(:x, :y) *
    (contour + mapping(color=:source)) * (data(df1) + data(df2))  # All scatters above all contours

draw(plt; axis)
```

![image](https://user-images.githubusercontent.com/2412819/119494547-b6209c80-bd61-11eb-945b-711c951049d2.png)

This is indeed better than using the same ordering as with heatmaps (datasets on the left of `*`), which paints contour lines on top of some markers:

```julia
plt = mapping(:x, :y) *
    (data(df1) + data(df2)) * (contour + mapping(color=:source))

draw(plt; axis)
```

![image](https://user-images.githubusercontent.com/2412819/119494451-9ab59180-bd61-11eb-933e-5be237010dd6.png)

So the way it works with right-distributivity seems reasonable to me...

**Comment by jtrakk** [comment]
@knuesel I can't see the difference between the two images in your first comment. Am I missing something?

**Comment by jtrakk** [comment]
@knuesel  It seems like you're optimizing for "scatter above contour". Maybe that wants to be the rule instead of `+` order?

**Comment by knuesel** [comment]
@jtrakk I think it's hard to predict what the user will want in every case. In the first case above, the contour should be in the foreground, but in the second case, in the background. I personally prefer "scatter above contour" so that would be a sensible default I think, *if* we're looking for a default. However:

* Do we want to define defaults for all possible combinations? That doesn't sound realistic.
* We would then need something additional to override the defaults
* User expect the order of layers to be reflected in the graphical results

To me it sounds more generally useful to have a well defined behavior for `+` and `*` that works intuitively in most cases (e.g. `a * (x + y)` and `(x + y) * a` when `a` is not composite) and still allows to control the order in more complex cases.
