### ISSUE TITLE
Faceting problem - ContinuousScale has no field plot

### ISSUE THREAD

**Issue by humphreylee** [JuliaPlots/AlgebraOfGraphics.jl#202]
Using modified example from the gallery [http://juliaplots.org/AlgebraOfGraphics.jl/dev/generated/gallery/#Faceting](url) 
`df = (x=rand(100), y=rand(100), l=rand([1, 2, 3, 4, 5], 100))
plt = data(df) * mapping(:x, :y, layout=:l)
draw(plt)`

The following error occurred `ERROR: LoadError: type ContinuousScale has no field plot`.

However, if the first line becomes `df = (x=rand(100), y=rand(100), l=rand(["1", "2", "3", "4", "5"], 100))`, then it is OK.

Technically, you might group the data by number as well, instead of just by string. Thanks.

**Comment by piever** [comment]
Thanks for the feedback.

Numeric fields correspond to continuous scales by default, so you'd need to do `layout = :l => nonnumeric` (can't really have a continuous variable informing layout). Documentation on scales is admittedly a bit lacking (docs PR welcome!), but the behavior itself should stay the same for consistency.

**Comment by humphreylee** [comment]
It works. Thanks.

**Comment by ew-git** [comment]
I know this is a closed issue, but original behavior doesn't cause an error, at least in v0.6.7. It just does nothing (i.e. no facet), which is pretty confusing. 
It would be helpful to check the type of the layout mapping and suggest the solution (`:l => nonnumeric`) in an error message.

Repro:
```julia
df = (x=rand(100), y=rand(100), l=rand([1, 2, 3, 4, 5], 100))
plt = data(df) * mapping(:x, :y, layout=:l)
draw(plt)
```
![plot_31](https://user-images.githubusercontent.com/38871370/172033508-07f221fe-7e70-43cb-9b07-b895e8dec9e8.png)

```julia
julia> versioninfo()
Julia Version 1.7.0-rc3
Commit 3348de4ea6 (2021-11-15 08:22 UTC)       
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code

julia> import Pkg; Pkg.status()
      Status `C:\Users\_\.julia\environments\v1.7\Project.toml`
  [cbdf2221] AlgebraOfGraphics v0.6.7 
  [13f3f980] CairoMakie v0.8.3        
  [324d7699] CategoricalArrays v0.10.6
  [861a8166] Combinatorics v1.0.2     
  [a93c6f00] DataFrames v1.3.4        
  [864edb3b] DataStructures v0.18.13  
  [abce61dc] Decimals v0.4.1
  [6fe1bfb0] OffsetArrays v1.12.1     
  [27ebfcd6] Primes v0.5.2
  [ce6b1742] RDatasets v0.7.7
  [a759f4b9] TimerOutputs v0.5.19
```
