### ISSUE TITLE
`xscale` with densities looks strange

### ISSUE THREAD

**Issue by ericphanson** [JuliaPlots/AlgebraOfGraphics.jl#205]
```julia
mwe = (; x = max.(0.1, randn(10000)))

plt = data(mwe) * mapping(:x => "x") * AlgebraOfGraphics.density()
draw(plt; axis = (; title="using `xscale=log10`", xscale=log10))
```
gives
 
![77b7957d-ff88-4a02-a934-f353ebf0b413](https://user-images.githubusercontent.com/5846501/120942925-3664db80-c72c-11eb-930d-dd5ff635ab4e.png)

while, using the same data,
```julia
plt = data(mwe) * mapping(:x => log10 => "log10(x)") * AlgebraOfGraphics.density()
draw(plt; axis = (; title="using transform in `mapping`"))
```
gives
![915e4d45-5c35-46f9-ae87-9f31ff5a0c5f](https://user-images.githubusercontent.com/5846501/120942941-3ebd1680-c72c-11eb-9c88-a36ecf70a498.png)

The difference looks even more extreme in my non-MWE data. I think these should be the same, right? Is there a bug somewhere?

**Comment by piever** [comment]
So, the order in which things happen is the following.

1. The transformation in `mapping` is applied
2. The analysis (eg `density`) is computed 
3. The scales are changed in the plot

Note that 3. (setting axis keywords like scale) does not affect 1. and 2. (things would get a bit too complex if it did), it just changes how the plot appears.

So it's actually expected that the two plots should be different, in that the first plot represents the `pdf` of `x` displayed in log scale (IMO, a slightly dangerous thing to do, as the total area will be different than `1`). The second plot represent the `pdf` of `log10(x)`, which differs from the first by a factor `1 / (x * log(10))`.

I confess I find the current behavior reasonable, but I agree it can be surprising. Is it a matter of documenting it (potentially in a FAQ), or do you think the behavior should change?

**Comment by ericphanson** [comment]
I see, I think the real problem then is my lack of understanding of what I was doing-- I forgot that

> the pdf of x displayed in log scale

and

> the pdf of log10(x), which differs from the first by a factor 1 / (x * log(10)).

were different. But of course they are, e.g. <https://math.stackexchange.com/a/613623>.

It's probably not the responsibility of AoG but I think a pointer to this difference somewhere could make sense-- I suspect more people will be using `density` who have't done a lot of KDE before (like me) just since AoG makes it so quick.

For the semantics, I agree that's reasonable behavior for AoG, and essentially what I expected.

**Comment by piever** [comment]
It's probably not the responsibility of AoG but I think a pointer to this difference somewhere could make sense-- I suspect more people will be using `density `who have't done a lot of KDE before (like me) just since AoG makes it so quick.

You are right that this is likely to trip people up, I'm adding some discussion about it in #206
