### ISSUE TITLE
Use of common names

### ISSUE THREAD

**Issue by jtrakk** [JuliaPlots/AlgebraOfGraphics.jl#207]
`data` is a generic and common variable name, and `mapping` is somewhat less so. It's a bit annoying that I can't conveniently use those names because they're occupied by AlgebraOfGraphics. I know there's a history of other names, but I am still wondering about alternative schemes. 

- `gdata`/`gmapping`/`gvisual` 
- `datalayer`/`maplayer`
- others... 

What do you think?

**Comment by piever** [comment]
Closing as I think it's important that these names stay simple. You can always do `AlgebraOfGraphics.data` if you end up accidentally shadowing the variable.
