### ISSUE TITLE
How to specify linestyle?

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaPlots/AlgebraOfGraphics.jl#209]
Hopefully this is just a quick question. How can I specify the linestyle for a particular line? I see that it is part of the theme, so can I specify at theme per layer?

**Comment by piever** [comment]
Yes, it's like any themable attribute, so in theory it should just work. Either `mapping(linestyle = :some_column)` if you want to change it in a data-dependent way, or `visual(linestyle = :dash)` if it is a data-independent setting.

**Comment by rikhuijzer** [comment]
Awesome. Got it :+1: Thanks!
