### ISSUE TITLE
stacked bar plots wrong?

### ISSUE THREAD

**Issue by ericphanson** [JuliaPlots/AlgebraOfGraphics.jl#216]
```julia
mwe_data = DataFrame(animal = rand(["cat", "mouse"], 1000), location = rand(["inside", "outside"], 1000))
draw(data(mwe_data) * frequency() * mapping(:location; color = :animal, stacked=:animal))
```
![image](https://user-images.githubusercontent.com/5846501/123527731-26646a00-d6e2-11eb-873c-a8dbaef04966.png)

```julia
draw(data(mwe_data) * frequency() * mapping(:location; color = :animal, dodge=:animal))
```
![image](https://user-images.githubusercontent.com/5846501/123527733-2bc1b480-d6e2-11eb-9a5f-c974d4b3c36d.png)

Looks like super different distributions! am I doing something wrong?

AlgebraOfGraphics v0.4.5
CairoMakie v0.6.1

**Comment by knuesel** [comment]
The keyword argument is `stack`, not `stacked`.

**Comment by ericphanson** [comment]
Oh! Thank you. I guess then the issue here is the Makie.jl thing of not erroring on extraneous keyword arguments, which is probably not an AoG issue.
