### ISSUE TITLE
colorrange ignored

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaPlots/AlgebraOfGraphics.jl#223]
```julia
df = data([(a=1, b=0.1), (a=2, b=0.2), (a=3, b=0.3)])
df * mapping(:a, color=:b) * visual(Scatter, colorrange=(0.0, 1.0)) |> draw
```
![image](https://user-images.githubusercontent.com/1010467/124144998-bc0a4b80-da8c-11eb-9df4-70eb27e2e9aa.png)

Is there any other way to set the colorrange?

**Comment by willcoxe** [comment]
Update: This doesn't seem to work for values < 1. So when I try to set a range from 0 to 0.5 for example, the colours are wrong.

**Comment by willcoxe** [comment]
Actually, nevermind. It does change the length of the colourbar in general but it doesn't change the colours in the graphic itself to match. I'm just going to use Makie on its own.
