### ISSUE TITLE
Pin AlgebraofGraphics in the JuliaPlots Org profile

### ISSUE THREAD

**Issue by storopoli** [JuliaPlots/AlgebraOfGraphics.jl#246]
Since `AbstractPlotting.jl` is archived, we could use the vacant space to pin `AlgebraOfGraphics.jl` in the JuliaPlots Organization profile.

![image](https://user-images.githubusercontent.com/43353831/127688472-4d7a032d-29fe-4774-965c-0283e68b3beb.png)

**Comment by SimonDanisch** [comment]
Good point, I took the liberty to just change those:
![image](https://user-images.githubusercontent.com/1010467/127689989-792fe0a1-d6df-49b2-9b62-2831a98e3851.png)

Also swapped out PlotUtils with PlotlyJS...
