### ISSUE TITLE
visual(Violin) creates box plot (not a violin plot)

### ISSUE THREAD

**Issue by roland-KA** [JuliaPlots/AlgebraOfGraphics.jl#264]
I have created a box plot and tried to create similar violin plot using AoG with `visual(Violin ...)`
 (see: https://github.com/roland-KA/StatisticalPlotsWithJulia, the violin plot and the box plot are in the Pluto notebook notebooks/DV-Basics-AlgebraOfGraphics.jl in section "Box Plots and Violin Plots").

But strangely the `visual(Violin)` creates exactly the same plot as does `visual(BoxPlot)`.

**Comment by piever** [comment]
I suspect this may be an issue in the notebook, in the `violin` section [here](https://github.com/roland-KA/StatisticalPlotsWithJulia/blob/main/notebooks/DV-Basics-AlgebraOfGraphics.jl#L330) it looks like you are still plotting `boxGDPperCapita` rather than `violinGDPperCapita`.

**Comment by roland-KA** [comment]
🤦‍♂️ ... thanks! That was copy&paste at work.
