### ISSUE TITLE
xscale does not compose with categorical data / dodge / Violin

### ISSUE THREAD

**Issue by tbenst** [JuliaPlots/AlgebraOfGraphics.jl#265]
Such an awesome package, thank you!

A few things undesired things here:
- left and right side of a violin are not symmetric
- one dodge to the next are different widths
- each category gets narrower

```julia
using AlgebraOfGraphics, CairoMakie, PalmerPenguins, DataFrames

set_aog_theme!() #src

penguins = dropmissing(DataFrame(PalmerPenguins.load()))

p1 = data(penguins) * visual(Violin) *
    mapping(:species, :bill_depth_mm, color=:sex, dodge=:sex)
draw(p1, axis=(xscale=log,))
```

![image](https://user-images.githubusercontent.com/863327/129846843-5ba62d01-2fa5-40a1-963e-697b617a227c.png)

**Comment by piever** [comment]
I confess I'm slightly confused. What would be the expected behavior of a log scale on a categorical axis? Did you mean to set `yscale = log`?

**Comment by tbenst** [comment]
I’m trying to visualize the difference between two distributions that have a long tail, and most of the difference lies in that tail. As such, I’d like the width of the violin to be log-density rather than density. I looked a bit of the code, and as best I can tell it seems like I would need to copy the code for Violin from Marie.jl, and write a new LogViolin function..?

or maybe there’s a way to apply the log scaling to each of the 6 xaxis that make up each violin..?

Gadfly’s approach is to have a “width” aesthetic that can be optionally supplied: http://gadflyjl.org/v0.5.0/lib/geoms/geom_violin.html

**Comment by piever** [comment]
Ah, now I get it, that makes a lot more sense. I think Gadfly's approach is correct (allow `violin` to take something other than a `kde` estimate), so I think one  should apply the same thing here (basically make a PR to Makie to generalize `violin` in that direction). 

Doing that directly with the axis is IMO not really possible, because there is only one axis objects where all violins are plotted.

**Comment by tbenst** [comment]
Closing as needs to be dealt with upstream
