### ISSUE TITLE
color scales are applied inconsistently between visuals with row/col mapping

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaPlots/AlgebraOfGraphics.jl#288]
MWE:

```julia
using AlgebraOfGraphics
using CairoMakie
using DataFrames

dd = DataFrame(x=repeat(["a", "b"], 4), y=rand(8), err=rand(8), color=1:8,
               col=repeat(["1", "2"], inner=2, outer=2),
               row=repeat(["1", "2"], inner=4, outer=1))

draw(data(dd) * mapping(:x, :y, :err; row=:row, col=:col, color=:color) * visual(Errorbars))
draw(data(dd) * mapping(:x, :y; row=:row, col=:col, color=:color) * visual(Scatter))
```
the color range seems to be computed using only the range of colors present in each subplot for Errorbars:
![image](https://user-images.githubusercontent.com/135920/136454104-7cff1429-0643-4dff-8925-5322f3f87ed8.png)

but across all panels for scatter (the expected behavior):
![image](https://user-images.githubusercontent.com/135920/136454127-d6b97e81-967e-464d-b74a-d937eeeff31d.png)

**Comment by piever** [comment]
Sorry for the slow reply! It seems like `Errorbars` does not support `colorrange`, compare:

```julia
julia> errorbars(0:10, 0:10, 0:10, color=0:10, colorrange=(0, 1000)) # colorrange is just ignored   

julia> scatter(0:10, 0:10, color=0:10, colorrange=(0, 1000)) # colorrange is respected
```

It should just be a matter of adding `colorrange` to the theme of `Errorbars`.
