### ISSUE TITLE
`hlines!` and `vlines!`

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaPlots/AlgebraOfGraphics.jl#299]
It's reasonably awkward to make use of `Makie`'s `hlines!/vlines!` with the output of `draw` since they operate on `Axis` types which aren't directly accessible to users and aren't "real" plot recipes/types that you could potentially use in a `visual(HLines)`-like manner (to my knowledge). My current approach is to do

```julia
function Makie.hlines!(fg::AlgebraOfGraphics.FigureGrid, args...; kws...)
	for axis in fg.grid
		hlines!(axis.axis, args...; kws...)
	end
	return fg
end
```

It does the job, but isn't that _nice_ and doesn't (in my mind) sit terribly well with the philosophy of AoG itself. Maybe this _is_ actually the right way to handle `hlines!` and `vlines!`, but perhaps there's a more streamlined approach that could be implemented for this that actually fits in with the rest of the API?

**Comment by likanzhan** [comment]
Do we now have an easy way to add hlines and vlines?

**Comment by karlwessel** [comment]
> Do we now have an easy way to add hlines and vlines?

Asked myself the same. For future me and others, here's is a solution
```julia
df = (y = [0.3863, 0.5307], 
    label = ["Poisson", "GOE"])

draw(data(df) * 
    mapping(:y, color=:label) * 
    visual(HLines, linestyle=:dash))
```
