### ISSUE TITLE
Wrong axis labelled in case of single mapping

### ISSUE THREAD

**Issue by knuesel** [JuliaPlots/AlgebraOfGraphics.jl#305]
For example:

```julia
draw(data((; height=[1.2, 1.3, 1.1, 1.1])) *
     mapping(:height);
     axis=(width=200, height=100))
```

![image](https://user-images.githubusercontent.com/2412819/141288188-8a4782aa-e1ad-422b-af12-608f7f6973c9.png)

I think the "height" label should be on the y axis, since that's the axis showing the height values.

**Comment by piever** [comment]
Thanks for the MWE, closing as dup of #97.
