### ISSUE TITLE
How to change the title of a legend?

### ISSUE THREAD

**Issue by onetonfoot** [JuliaPlots/AlgebraOfGraphics.jl#317]
I'm struggling to figure out how to change the title of a legend?

**Comment by piever** [comment]
Hi, it should work using the pair syntax, that is `mapping(color = column => "some label")`, same as is used for changing the axis labels [here](http://juliaplots.org/AlgebraOfGraphics.jl/dev/gallery/gallery/data%20manipulations/new_columns_on_the_fly/#Renaming-(including-LaTeX-labels)-and-transforming-variables). It's true that there is no example for the legend (it may be worth adding) but the same principles apply.

**Comment by onetonfoot** [comment]
Thanks for your help! Yeah it is very intuitive once you get it, however it took me a while to figure this out and also how to sort the legend. I'll submit a pull request to update the [legend-tweaking](http://juliaplots.org/AlgebraOfGraphics.jl/dev/gallery/gallery/customization/legend/#Legend-tweaking) section to make it a little more obvious
