### ISSUE TITLE
Histogram bin widths are constant

### ISSUE THREAD

**Issue by fedario** [JuliaPlots/AlgebraOfGraphics.jl#332]
Hi and thank you for this great package!

Here is a minimal example code to generate a simple histogram of normal distributed sample:

```Julia
using DataFrames
using Distributions
using GLMakie
using AlgebraOfGraphics


n_points = 100_000
data_raw = rand(Normal(0, 1), n_points)
df = DataFrame(:variable_1 => data_raw)

test_plot = data(df) * mapping(:variable_1) * AlgebraOfGraphics.histogram(bins=1000)

fig = draw(test_plot)

save("test_plot.png", fig)
```
The resulting figure I get looks like this:

![test_plot](https://user-images.githubusercontent.com/24253179/151805158-b3b26fc2-f9db-4c37-a1f9-a18e76730d40.png)

It seems like the width of the bins is wrong and does not adapt to their number.
Or perhaps I'm using the package wrong?

Versions:
julia version 1.7.1
[cbdf2221] AlgebraOfGraphics v0.6.1
[e9467ef8] GLMakie v0.5.2
[a93c6f00] DataFrames v1.3.2
[31c24e10] Distributions v0.25.42

**Comment by piever** [comment]
Thanks for reporting that! Definitely a bug in the latest release... I've opened #333 to fix it, should be merged and released as soon as tests and doc generation passes.
