### ISSUE TITLE
Negative values in density plot

### ISSUE THREAD

**Issue by fedario** [JuliaPlots/AlgebraOfGraphics.jl#334]
Hi again!

I have found a potential bug when creating a density plot in some contexts.

```Julia
using CSV
using DataFrames
using GLMakie
using AlgebraOfGraphics

data_df = CSV.read("testdata.csv", DataFrame)

data_plot = (
    data(data_df)
    * mapping(:value, col=:variable)
    * AlgebraOfGraphics.density(npoints=1000)
)

fig = draw(data_plot)
```

Produces (zoomed section):
![image](https://user-images.githubusercontent.com/24253179/151871480-50209635-7735-44d5-ad7f-f1a631b4085e.png)

Dataset used:
[testdata.csv](https://github.com/JuliaPlots/AlgebraOfGraphics.jl/files/7974192/testdata.csv)

Unfortunately I wasn't able to reproduce this with other datasets so far.

Versions:
julia version 1.7.1
[cbdf2221] AlgebraOfGraphics v0.6.1
[e9467ef8] GLMakie v0.5.2
[a93c6f00] DataFrames v1.3.2
[336ed68f] CSV v0.10.2

**Comment by knuesel** [comment]
Seems like a bug in KernelDensity.jl, probably [this one](https://github.com/JuliaStats/KernelDensity.jl/issues/29). Here's an MWE:

```julia
df = CSV.read("testdata.csv", DataFrame)
b = df.value[df.variable .== "b"];
rng = range(extrema(b)..., length=1000)
k = kde(b)
interp = pdf(k, rng)
```

The negative values are introduced by the interpolation down by `pdf`:

![image](https://user-images.githubusercontent.com/2412819/151975601-0403d3ce-aa1b-43cf-8050-3eba02bc6c27.png)

**Comment by piever** [comment]
Thanks for the report! I'm closing the issue here as there is nothing actionable on the AlgebraOfGraphics side, the bug should be fixed at KernelDensity.
