### ISSUE TITLE
Wrong axis when plotting Bar plot horizontally

### ISSUE THREAD

**Issue by rongcuid** [JuliaPlots/AlgebraOfGraphics.jl#355]
For instance:

```julia
data(df) * mapping(:x, :y) * visual(BarPlot, direction = :x) |> draw
```

In this case, the bar plot will plot `x` on vertical axis and `y` on horizontal axis. However, the ticks and x/y labels are wrong.

I am still new to julia plotting, so I might be missing something obvious. I require horizontal plotting because I've got some long labels that are hard to lay out vertically.

**Comment by piever** [comment]
You're doing everything correctly, simply the horizontal orientation is not yet supported in AlgebraOfGraphics (see also #335 and https://github.com/JuliaPlots/Makie.jl/issues/926).  Hopefully, it should be possible to address this with the next breaking Makie release.

**Comment by rongcuid** [comment]
Is there a hack available? I tried the recipe in #926, but that produced an plot like this

![Screenshot from 2022-02-24 09-08-34](https://user-images.githubusercontent.com/1312525/155539515-a4f322e0-ff1b-42e4-8a1d-92a393e77b7f.png)

**Comment by piever** [comment]
The only other hack I can think of is to manually do

```julia
plt = data(df) * mapping(:x, :y) * visual(BarPlot, direction = :x)
draw(plt, axis=(yticks=(1:2, ["a", "b"]), yaxislabel="interval", xticks=..., xaxislabel=...)
```

See the [Makie axis docs](https://makie.juliaplots.org/dev/examples/layoutables/axis/index.html#modifying_ticks) for details on how to do this.

**Comment by rongcuid** [comment]
But at that point I might be better off using Makie directly.

Is the issue something AoG simply can't do, or is it just waiting for the Makie API to stabilize? I briefly read the code, and seems like AoG is already preprocessing some of its arguments like `dodge`.

**Comment by piever** [comment]
> But at that point I might be better off using Makie directly.

Yes, whenever you run into something unsupported here, that's always a reasonable option.

I don't think it is impossible to support this, but it will be easier once Makie stabilizes on this (unified interface to determine with certainty which variable is associated to which axis).

**Comment by roland-KA** [comment]
Just to get it clear: This means, it is still not possible to plot a horizontal box plot using AoG?
