### ISSUE TITLE
Unable to draw at grid position

### ISSUE THREAD

**Issue by rongcuid** [JuliaPlots/AlgebraOfGraphics.jl#359]
I am trying to do gridded plots which combine Makie plots and several AoG plots, with something like this:

```julia
    axis = (title = title,)
    fg = draw!(figure[1,1], plot; axis)
    legend!(figure[1,2], fg)
```

This works only if `figure` is a `Figure`, but not `FigurePosition`, since I get this error:

```
ERROR: LoadError: MethodError: no method matching legend!(::GridSubposition)
Closest candidates are:
  legend!(::Any, ::Any; kwargs...) at ~/.julia/packages/AlgebraOfGraphics/8WZVt/src/guides/legend.jl:14
  legend!(::AlgebraOfGraphics.FigureGrid; position, orientation, kwargs...) at ~/.julia/packages/AlgebraOfGraphics/8WZVt/src/guides/legend.jl:1
```

So I cannot find a good way to combine figures.

**Comment by piever** [comment]
Could you please provide a MWE?

**Comment by rongcuid** [comment]
I don't know what's happening, but it worked again, including the original code...

But anyways, this is the example I tried to reproduce:

```julia
using CairoMakie
using AlgebraOfGraphics
##
dat1 = (x = [1, 1, 2, 2], y = [5, 6, 7, 8], group = [:A, :B, :A, :B])
plt1 = data(dat1) * mapping(:x, :y, stack = :group, color = :group) * visual(BarPlot)
axis = (title = "A",)
##
# Simple working example
fig1 = draw(plt1; axis)
fig1
##
# Simple working manual plot
fig2 = Figure()
ag2 = draw!(fig2[1, 1], plt1; axis)
legend!(fig2[1, 2], ag2)
fig2
##
fig3 = Figure()
fp3 = fig3[1, 1]
ag3 = draw!(fp3[1, 1], plt1; axis)
legend!(fp3[1, 2], ag3)
fig3
```
I expected fig3 to fail, but it didn't. I don't know if there was lingering global state in REPL or sometihng that caused the original problem or not.

**Comment by piever** [comment]
No problem, closing here because there doesn't seem to be anything actionable. Feel free to reopen if you find an MWE where things don't work as expected.
