### ISSUE TITLE
linkxaxes doesn't affect histograms

### ISSUE THREAD

**Issue by andreasnoack** [JuliaPlots/AlgebraOfGraphics.jl#372]
## Bug description

When plotting faceted histograms, `facet=(;linkxaxes=:minimal))` does not seem to affect the xaxis so if the location of the data varies a lot then the histograms have all the data lumped in a single bin. See picture below

## Steps to reproduce

```julia
julia> df = DataFrame(gr = repeat(1:2, inner=10, outer=10));

julia> transform!(df, :gr => ByRow(string) => :grs);

julia> transform!(df, :gr => ByRow(t -> ifelse(t == 1, 100, 0) + randn()) => :x);

julia> draw(data(df) * mapping(:x, col=:grs) * histogram(), facet=(;linkxaxes=:minimal))
```

## Images

<img width="602" alt="Skærmbillede 2022-03-17 kl  08 25 37" src="https://user-images.githubusercontent.com/505001/158758540-c14f6934-12af-4433-93dd-729a582f0e23.png">

## Version info

julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
  JULIA_PKG_SERVER = pumasai.juliahub.com

(@v1.7) pkg> st
      Status `~/.julia/environments/v1.7/Project.toml`
  [cbdf2221] AlgebraOfGraphics v0.6.5
  [6e4b80f9] BenchmarkTools v1.3.1
  [336ed68f] CSV v0.10.3
  [13f3f980] CairoMakie v0.7.4
  [324d7699] CategoricalArrays v0.10.4
  [944b1d66] CodecZlib v0.7.0
  [a93c6f00] DataFrames v1.3.2
  [1313f7d8] DataFramesMeta v0.10.0
  [31a5f54b] Debugger v0.7.6
  [f3b72e0c] DiffEqDevTools v2.29.0
  [31c24e10] Distributions v0.25.49
  [e30172f5] Documenter v0.27.14
  [35a29f4d] DocumenterTools v0.1.13
  [d4d017d3] ExponentialUtilities v1.13.0
  [26cc04aa] FiniteDifferences v0.12.24
  [f6369f11] ForwardDiff v0.10.25
  [38e38edf] GLM v1.6.1
  [14197337] GenericLinearAlgebra v0.2.7
  [682c06a0] JSON v0.21.3
  [ff71e718] MixedModels v4.6.1
  [9b87118b] PackageCompiler v2.0.5
  [c3e4b0f8] Pluto v0.18.2
  [f27b6e38] Polynomials v3.0.0
  [132c30aa] ProfileSVG v0.2.1
  [33c8b6b6] ProgressLogging v0.1.4
  [c6596682] QuantileRegressions v0.1.10
  [94ee1d12] Quaternions v0.5.3
  [6f49c342] RCall v0.13.13
  [ce6b1742] RDatasets v0.7.7
  [97cc5700] RNGTest v1.5.1
  [52522f7a] ReadStatTables v0.1.1
  [324d217c] ReferenceTests v0.9.10
  [295af30f] Revise v3.3.3
  [1bc83da4] SafeTestsets v0.0.1
  [aa65fe97] SnoopCompile v2.9.1
  [e2b509da] SnoopCompileCore v2.9.0
  [860ef19b] StableRNGs v1.0.0
  [90137ffa] StaticArrays v1.2.5
  [2913bbd2] StatsBase v0.33.16
  [4c63d2b9] StatsFuns v0.9.15
  [88034a9c] StringDistances v0.11.2
  [c3572dad] Sundials v4.9.3
  [dcd651b4] TestReports v0.6.3
  [ac1d9e8a] ThreadsX v0.1.9
  [3bb67fe8] TranscodingStreams v0.9.6
  [b8865327] UnicodePlots v2.9.0
  [a4e569a6] Tar

**Comment by piever** [comment]
Thanks for reporting this! I suspect the problem is that the axis are actually not linked, but bins are computed globally, and the "empty bins" prevent the resizing of the axes (see for instance [this discourse question](https://discourse.julialang.org/t/is-x-axis-linking-ignored-in-algebra-of-graphics/76111)).

You can specify that you want the "bin range" to be computed by hand with `histogram(datalimts=extrema)`, which is applied trace by trace (taking the `extrema` of the data for each trace). Ideally we would have `histogram(datalimits=:subplot)` to do it by subplot as well, ref #199, otherwise `histogram(datalimits=extrema)` can be problematic if you do a stacked barplot with inconsistent bins across traces.

**Comment by andreasnoack** [comment]
Ah. Indeed `datalimits=extrema` fixes my issue here. It would be great with an example of this in the docs.
