### ISSUE TITLE
density() datalimits do not adjust for different columns

### ISSUE THREAD

**Issue by filchristou** [JuliaPlots/AlgebraOfGraphics.jl#399]
The density() function by default works in the minimal data space.
But when I want to plot per columns the values of all the columns are being considered.

```julia
using RDatasets, AlgebraOfGraphics
AoG = AlgebraOfGraphics
set_aog_theme!()

iris = dataset("datasets", "iris")

props = filter(!=(:Species),propertynames(iris))[:,:]
```

The behavior of AoG:
```julia
let
	plt = data(iris) * AoG.density() * mapping(props, col=dims(1), color = :Species)
	draw(plt)
end
```
![image](https://user-images.githubusercontent.com/27723218/171875375-35e99ec5-5728-4704-af6c-951903b27799.png)

But if I plot each column discrete and then plot the result I get the desired output
```julia
let
	fig = Figure()
	plts = [data(iris) * (mapping(prop, color = :Species)) * AoG.density() for prop in props]
	[draw!(fig[1,i], plts[i]) for i in 1:length(props)]
	fig
end
```
![image](https://user-images.githubusercontent.com/27723218/171875319-fb619338-79f4-4f7d-8ff9-1edff407d212.png)

I think the first case should generate something similar to the second case.

**Comment by piever** [comment]
By design the data limits of the density are computed over the whole data. If you want to only show the density within the extrema of the data (on a group by group basis), you can use

```julia
AoG.density(datalimits=extrema)
```

instead. (You would also need to unlink the axes of the facet to get the second plot with a unique call.)
