### ISSUE TITLE
Adjusting the legend position

### ISSUE THREAD

**Issue by greimel** [JuliaPlots/AlgebraOfGraphics.jl#40]
Is there a way to adjust the legend position?

Is there a way to access the legend of a plot?

In MakieLayout it seems to be easy to move stuff around (and also adjusting things like orientation). But I guess, the output of a AoG plot is a plain scene, and not a (scene, layout), right?

**Comment by greimel** [comment]
Thanks to @asinghvi17 on Slack and the fabulous MakieLayout tutorial by @jkrumbiegel, I solved the problem.

```julia
using AlgebraOfGraphics, AbstractPlotting, CairoMakie
x = rand(100)
g = rand(["very loooong","looooong"], 100)
df = DataFrame(g = g, x = x, y = (g .== "very") .+ x .+ randn(100))

cols = style(:x, :y);
grp = style(color = :g)
scat = spec(Scatter)
pipeline = cols * scat
aog = data(df) * grp * pipeline

aog |> draw
```

![v1](https://user-images.githubusercontent.com/6280307/80636680-21fcdc80-8a5e-11ea-9b9e-e243bae4ce92.png)
```julia
scene, layout = MakieLayout.layoutscene()
AlgebraOfGraphics.layoutplot!(scene, layout, aog)

#lax = layout.content[1].content.content[1].content
leg = layout.content[2].content
layout[0,1] = leg
leg.tellheight = true
leg.tellwidth = false
leg.orientation = :horizontal
leg.titleposition = :left

trim!(layout)
scene
```
![v2](https://user-images.githubusercontent.com/6280307/80636695-275a2700-8a5e-11ea-88bb-72067ac54fb7.png)

If you think this would be helpful to have in the docs, I can submit a PR. (Or feel free to use the code here)

**Comment by piever** [comment]
Yes, by all means, docs PR are always welcome!

I suspect by default one could also have `layoutplot` return both the layout and the scene, as long as `draw` only returns one "plottable thing". Alternatively (which IMO would be even better) MakieLayout could somehow be restructured so that both scene and layout belong to a unique object that displays as a plot.

**Comment by jkrumbiegel** [comment]
Yes, I think each scene should contain a layout by default (basically the same configuration that `layoutscene` creates, where the layout moves to track the `px_area` of the Scene) once we do the MakieLayout merge. Then you wouldn't have to pass the layout around, too.

**Comment by greimel** [comment]
Here is a function that can be used to customize the legend.

```julia
using AlgebraOfGraphics, AbstractPlotting, CairoMakie
using MakieLayout
using UnPack

default_orientation(legend_position) = legend_position in [:top, :bottom] ? :horizontal : :vertical
default_titleposition(orientation) = orientation == :horizontal ? :left : :top

function legend_position!(scene, layout, position;
                          orientation=default_orientation(position),
                          titleposition=default_titleposition(orientation))
    outer_layout = layout
    outer_axs = outer_layout.content
    
    cont_leg = outer_axs[2]
    cont_plt = outer_axs[1]
    
    leg = cont_leg.content
    layout_inner = cont_plt.content
    
    @unpack rows, cols = cont_plt.span
    
    if position == :top
        outer_layout[rows .- 1, cols] = leg
    elseif position == :bottom
        outer_layout[rows .+ 1, cols] = leg
    elseif position == :left
        outer_layout[rows, cols .- 1] = leg
    elseif position == :right
        outer_layout[rows, cols .+ 1] = leg
    else
        @error "position $position not supported"

    end
      
    if position in [:top, :bottom]
        leg.tellheight = true
        leg.tellwidth = false
    else # if position in [:left, :right]
        leg.tellheight = false
        leg.tellwidth = true
    end
    
    leg.orientation = orientation
    leg.titleposition = titleposition
    
    trim!(outer_layout)
    scene
end
```

To illustrate,

```julia
using RDatasets

mpg = dataset("ggplot2", "mpg")
mpg[!,:grpx] .= rand.(Ref(["a", "b", "c"]))
mpg[!,:grpy] .= rand.(Ref(["aa", "bb"]))

cols = style(:Displ, :Hwy)
grp = style(color = :Cyl => categorical, layout_x = :grpx, layout_y = :grpy)
scat = spec(Scatter)
pipeline = cols * scat
aog = data(mpg) * grp * pipeline

scene, layout = MakieLayout.layoutscene()
AlgebraOfGraphics.layoutplot!(scene, layout, aog)

legend_position!(scene, layout, :bottom)
```
![legend_bottom](https://user-images.githubusercontent.com/6280307/86933303-b2305f80-c13a-11ea-91da-51bf4173c042.png)
```julia
legend_position!(scene, layout, :left)
```
![legend_left](https://user-images.githubusercontent.com/6280307/86933334-b9f00400-c13a-11ea-9a3a-525b331821dd.png)
```julia
legend_position!(scene, layout, :top)
```
![legend_top](https://user-images.githubusercontent.com/6280307/86933358-bfe5e500-c13a-11ea-867a-300558099d80.png)
```julia
legend_position!(scene, layout, :right)
```
![legend_right](https://user-images.githubusercontent.com/6280307/86933379-c5432f80-c13a-11ea-9b60-eb126856e689.png)

**Comment by greimel** [comment]
The function above works for AoG plots, because they consist of some inner layout and a legend and nothing more.

Should such functionality be part of AoG? Or of a different package?

Or should one strive for a more general solution in AbstractPlotting?

**Comment by piever** [comment]
Closing as now legend position is customizable.
