### ISSUE TITLE
Faceting with empty panels is broken

### ISSUE THREAD

**Issue by greimel** [JuliaPlots/AlgebraOfGraphics.jl#50]
After your comment in #46 I tried this on master and this currently broken.

```julia
Pkg.pkg"add https://github.com/JuliaPlots/CairoMakie.jl#pv/update"
using RDatasets, CairoMakie, AbstractPlotting, AlgebraOfGraphics
using Underscores, DataFrames

mpg = dataset("ggplot2", "mpg")
mpg[!,:grpx] .= rand.(Ref(["a", "b", "c"]))
mpg[!,:grpy] .= rand.(Ref(["aa", "bb"]))

# remove data to get empty panels
dta = @_ mpg |> 
    filter(!((_.grpx == levels(__.grpx)[1]) & (_.grpy == levels(__.grpy)[1])), __) |>
    filter(!((_.grpx == levels(__.grpx)[2]) & (_.grpy == levels(__.grpy)[2])), __) |>
    data
    

cols = style(:Displ, :Hwy)
grp = style(color = :Cyl => categorical, layout_x = :grpx, layout_y = :grpy)
scat = spec(Scatter)
pipeline = cols * scat
aog = dta * grp * pipeline
scn = aog |> draw
```

![empty-panels](https://user-images.githubusercontent.com/6280307/87310023-a5867f80-c51d-11ea-8f81-3f7fe3415f30.png)

I would expect there to be x and y labels everywhere.

**Comment by piever** [comment]
Oh, I see. I'll just go ahead and merge #46 because it seems a strict improvement over the current situation and there's not much point in fine-tuning the code now because I'll go through a largish rework of the internals in the next few days.

**Comment by greimel** [comment]
Thanks!

**Comment by greimel** [comment]
I almost have code to fix this. So for the xlabel in the first column I would check if all non-empty panels have identical (shown and hidden) xlabels. 

And then I would compare the columns and check if the labels can be replaced by spanned labels.

The second part (detection if axis label is spannable) looks like this:

It detects if in a layout the axes are spannable. It returns a NamedTuple `(; x::Union{Nothing,String}, y::Union{Nothing,String}`. If the xlabel is not spannable then `x = nothing`, if it is spannable `x` holds the common xlabel.

```julia
function spannable(layout)
    labs = map(layout.content) do _ax
        ax = _ax.content
        (x = ax.xlabel[], y = ax.ylabel[], empty = isemptyax(ax))
    end |> StructArray
    
    unique_x_labs = unique(labs.x[.! labs.empty])
    unique_y_labs = unique(labs.y[.! labs.empty])
    
    xlab = length(unique_x_labs) == 1 ? only(unique_x_labs) : nothing
    ylab = length(unique_y_labs) == 1 ? only(unique_y_labs) : nothing
    
    (x = xlab, y = ylab)
end

isemptyax(ax) = length(ax.scene.plots) == 0
```

Is it worth preparing a PR or do you plan to fix this earlier in the pipeline?

**Comment by piever** [comment]
Ah yes, I was also considering something along those lines (if they are all the same in practice, just write it once "spanned").

Yes, do make a PR, this seems independent on the refactor (which is more about how things are stored internally).
