### ISSUE TITLE
Multiple legends cleanup

### ISSUE THREAD

**Issue by piever** [JuliaPlots/AlgebraOfGraphics.jl#57]
Two issues at the moment:

- [x] It often tries to superimpose things when it shouldn't (should be solved with https://github.com/JuliaPlots/AlgebraOfGraphics.jl/pull/56)
- [ ] Things like marker legend should be black, rather than taking the color from the first series (may need to use manually `LegendElement`).

**Comment by greimel** [comment]
stuff like this should work

![image](https://user-images.githubusercontent.com/6280307/91709239-c2851980-eb82-11ea-9ae4-6b232ad2c54b.png)

- [ ] `colorbar` should be integrated to the legends framework, unlink what I've started in #84 
- [ ] add support for `markersize`

**Comment by piever** [comment]
Closed by #155
