### ISSUE TITLE
Uninformative error for column typos

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaPlots/AlgebraOfGraphics.jl#99]
Currently, if one writes the name of a data column incorrectly and it's not found, the code errors when a `findfirst` call returning `nothing` is supposed to be coerced to an `Int` index. So the error thrown is:

```julia
ERROR: LoadError: MethodError: Cannot `convert` an object of type Nothing to an object of type Int64
Closest candidates are:
  convert(::Type{T}, ::AbstractPlotting.Unit) where T<:Number at C:\Users\krumbiegel\.julia\packages\AbstractPlotting\lGPof\src\units.jl:31 
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  ...
Stacktrace:
 [1] getcolumn(::AlgebraOfGraphics.ColumnDict, ::Symbol) at C:\Users\krumbiegel\.julia\packages\AlgebraOfGraphics\chGdQ\src\utils.jl:11     
 [2] extract_column(::AlgebraOfGraphics.ColumnDict, ::Pair{Symbol,typeof(identity)}) at C:\Users\krumbiegel\.julia\packages\AlgebraOfGraphics\chGdQ\src\context.jl:164
```

I would suggest that rather than writing a more informative message right at that point, this problem should be handled further up the chain so that we can say "invalid column name $xyz for keyword `color` / positional argument 2 / etc."

**Comment by piever** [comment]
I agree, that error is really not great. For now I'm adding a better one in #100, in the future we can think if there is a smart way to catch this further up (probably already when multiplying the data with the mapping).

**Comment by jkrumbiegel** [comment]
I'm going to close this, we can always look for a more complete solution later :)
